version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/questions_db?sslmode=disable
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=questions_db
    volumes:
      - db_data:/var/lib/postgresql/data
  python_generator:
    build: ./python_generator
    depends_on:
      - app
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/questions_db?sslmode=disable
volumes:
  db_data: